### ISSUE TITLE
Remove support of IE11

### ISSUE THREAD

**Issue by liesahead** [ali-hm/angular-tree-component#3]
This would decrease the bundle size. The newer versions of angular do not support IE11 anyway.

**Comment by ali-hm** [comment]
If you mean to remove polyfills that are to support IE9, IE10 and IE11, I will consider it in the next release.

**Comment by ali-hm** [comment]
If you have any other idea to make this component better I will be happy to hear.

**Comment by liesahead** [comment]
@ali-hm , angular throws warnings about optimization bailout due to “mobx” library. I thought maybe there’s some update to this library or modern version is released so it could be replaced?

**Comment by ali-hm** [comment]
I will try to update "mobx" lib in the next release.

**Comment by liesahead** [comment]
Great, thanks!
