### ISSUE TITLE
Add Support for Angular 18

### ISSUE THREAD

**Issue by EMC2x** [ali-hm/angular-tree-component#6]
We are encountering a compatibility issue with ng-recaptcha when upgrading our project to Angular 18. While the ng-recaptcha package lists Angular versions >=14 as compatible, we are receiving peer dependency errors when trying to install it with Angular 18. Specifically, the error indicates a conflict due to the package's peer dependency requiring @angular/core@^17.0.0.

To bypass this issue, we used the --force flag to install the dependencies, and after testing, our application compiles, serves, and runs as expected with Angular 18. However, relying on --force is not ideal for our CI/CD pipeline, as it introduces risk and uncertainty in automated processes.

We are looking for an official update to ng-recaptcha that explicitly supports Angular 18, so we can avoid using --force in our builds and ensure long-term compatibility. Below are the details of the error and logs from the installation process:
`npm ERR!   @angular/core@"18.2.7" from the root project`
`npm ERR!   peer @angular/core@">=14.0.0" from @ali-hm/angular-tree-component@12.0.5`
`npm ERR!   node_modules/@ali-hm/angular-tree-component`
`npm ERR!     @ali-hm/angular-tree-component@"^12.0.5" from the root project`
`npm ERR!   8 more (@angular/animations, @angular/common, ...)`

**Comment by ali-hm** [comment]
Sorry for late answer. I had tried to update it to angular 18 but it failed somehow and I give it another try and inform you for the results.

**Comment by ali-hm** [comment]
The component has been updated Angular 18 and the test were ok. the versioning (major version) has been changed to align with minimum angular version supported.

**Comment by EMC2x** [comment]
Thank you for the quick and timely response! We will update our package version now. Thank you!
